FROM rocketchat/rocket.chat.preview:3.12.1

# Here I use the "preview" image because it deploys a container with a database inside
# it's useful for quickly trying or running tests, not requiring a dedicated database installation

# Setup is at http://localhost:13000/setup-wizard/1